### ISSUE TITLE
Error when attemping extract of cramfs image

### ISSUE THREAD

**Issue by tridentsx** [AT0myks/pycramfs#1]
My test:/home/tridentsx/dumps/test/backup/nand/09-06-2023_17-21/fma5.img
WARNING: old cramfs format
Traceback (most recent call last):
  File "/home/tridentsx/dumps/./test.py", line 43, in <module>
    unpack_dump("./backup_176.zip")
  File "/home/tridentsx/dumps/./test.py", line 33, in unpack_dump
    extract_dir(rootdir, "fma5")  # Extract a directory tree
  File "/usr/local/lib/python3.10/dist-packages/pycramfs/extract.py", line 108, in extract_dir
    path.mkdir(file.mode, exist_ok=force)
AttributeError: 'PurePosixPath' object has no attribute 'mkdir'

**Comment by AT0myks** [comment]
`extract_dir` expects `dest` to be a `Path` so the fix is to do
```py
from pathlib import Path
extract_dir(rootdir, Path("fma5"))
```
This is not obvious unless you have type checking enabled in your editor. To avoid the same issue in the future I might change it so that it also accepts a `str`, that way it'll be more natural.
